### ISSUE TITLE
关于初始化Raft节点的问题

### ISSUE THREAD

**Issue by sunzheng86** [eraft-io/eraft#136]
您好：
在阅读代码时遇到一个疑问：
raft.go代码初始化Raft节点时对该raft节点的日志进行了初始化：newraft.ReInitLog(),该初始化过程删除了所有日志，
raft论文中logs日志时持久化保存的，为什么在代码中每次启动都要清空日志呢？
而且清空日志后，接下来执行了如下代码
newraft.matchIdx[peer.id], newraft.nextIdx[peer.id] = 0, int(LastLogIndex)+1
这样每次matchidx和nextidx都为0和1了？
不理解为什么每次启动程序就要删除所有日志，而不是加载已经持久化的日志呢？

**Comment by LLiuJJ** [comment]
> 

当时为了测试快照
