### ISSUE TITLE
Is there a concurrency problem with RaftLog's Append?

### ISSUE THREAD

**Issue by hjrbill** [eraft-io/eraft#197]
Does RaftLog's Append function have concurrency issues? In Append, you didn't lock, but you went through all the logs to get the lastLogID. I think such an operation might result in the same Index being generated when inserting

**Comment by LLiuJJ** [comment]
> Does RaftLog's Append function have concurrency issues? In Append, you didn't lock, but you went through all the logs to get the lastLogID. I think such an operation might result in the same Index being generated when inserting

If there is a concurrent Append log scenario, concurrency competition problems may occur, you can commit a bug fix for it.

**Comment by hjrbill** [comment]
Sure, I'll submit a commit to address this issue later.

**Comment by hjrbill** [comment]
> > Does RaftLog's Append function have concurrency issues? In Append, you didn't lock, but you went through all the logs to get the lastLogID. I think such an operation might result in the same Index being generated when inserting↳
> 
> If there is a concurrent Append log scenario, concurrency competition problems may occur, you can commit a bug fix for it.↳

I have opened a [pr](https://github.com/eraft-io/eraft/pull/200) to address this issue and look forward to your comments.
