### ISSUE TITLE
Protoc generated CPP files should not be dependent on the specific Protobuf version.

### ISSUE THREAD

**Issue by yuzhishuo** [eraft-io/eraft#52]
in the high version, building the project generate error as follow:

![image](https://user-images.githubusercontent.com/19743727/150911901-849359cc-8c1a-49a7-b5da-bd8c13bf0e04.png)

**Comment by LLiuJJ** [comment]
try to cancel general_cpp.sh comments in build script
![C81C17A6-4C24-4ECF-BB81-694B2A7691D9](https://user-images.githubusercontent.com/37827810/150913439-b6aea553-9f7b-489b-8c94-1691e29b2c8f.jpeg)

**Comment by LLiuJJ** [comment]
> in the high version, building the project generate error as follow:
> 
> ![image](https://user-images.githubusercontent.com/19743727/150911901-849359cc-8c1a-49a7-b5da-bd8c13bf0e04.png)

try to cancel general_cpp.sh comments in build script
![C81C17A6-4C24-4ECF-BB81-694B2A7691D9](https://user-images.githubusercontent.com/37827810/150913439-b6aea553-9f7b-489b-8c94-1691e29b2c8f.jpeg)

**Comment by LLiuJJ** [comment]
> in the high version, building the project generate error as follow:
> 
> ![image](https://user-images.githubusercontent.com/19743727/150911901-849359cc-8c1a-49a7-b5da-bd8c13bf0e04.png)

try to cancel general_cpp.sh comments in build script
![C81C17A6-4C24-4ECF-BB81-694B2A7691D9](https://user-images.githubusercontent.com/37827810/150913439-b6aea553-9f7b-489b-8c94-1691e29b2c8f.jpeg)

**Comment by yuzhishuo** [comment]
get it., thanks.
